import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// ==========================================
// Push Notification Handler
// ==========================================
self.addEventListener('push', (event) => {
  let data = { title: 'Jokskuy', body: 'Ada notifikasi baru!', url: '/' }

  try {
    if (event.data) {
      data = { ...data, ...event.data.json() }
    }
  } catch (e) {
    if (event.data) {
      data.body = event.data.text()
    }
  }

  const options = {
    body: data.body,
    icon: '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/',
      notificationId: data.notificationId || null,
    },
    actions: [
      { action: 'open', title: 'Buka' },
      { action: 'close', title: 'Tutup' },
    ],
    tag: data.tag || 'jokskuy-notification',
    renotify: true,
  }

  event.waitUntil(self.registration.showNotification(data.title, options))
})

// ==========================================
// Notification Click Handler
// ==========================================
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  if (event.action === 'close') return

  const url = event.notification.data?.url || '/'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Focus existing window if available
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus()
          client.navigate(url)
          return
        }
      }
      // Open new window
      return self.clients.openWindow(url)
    })
  )
})

// ==========================================
// Activate — claim clients + re-validate push subscription
// ==========================================
self.addEventListener('activate', (event) => {
  event.waitUntil(
    self.clients.claim().then(async () => {
      // After SW update, check if push subscription is still alive
      // If not, notify all clients to re-subscribe
      try {
        const subscription = await self.registration.pushManager.getSubscription()
        if (!subscription) {
          console.log('[SW] Push subscription lost after update, notifying clients...')
          const clients = await self.clients.matchAll({ type: 'window' })
          for (const client of clients) {
            client.postMessage({ type: 'PUSH_SUBSCRIPTION_LOST' })
          }
        } else {
          console.log('[SW] Push subscription still valid after update')
        }
      } catch (err) {
        console.error('[SW] Error checking push subscription on activate:', err)
      }
    })
  )
})
